name:CI

on:
 push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
  steps:
      - name: Checkout source
        uses: actions/checkout@main
        with:
            ref: main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
              node-version: '14'
      - name: Install and Build
      run: |
        npm install
        npm run build 